# Matrices y Arrays

Al trabajar con algebra lineal utilizamos el concepto de matriz, entendiéndose a una matriz como un arreglo bidimensional de números. Las matrices son designadas por letras mayúsculas y poseen dos subíndices los cuales hacen referencia a la cantidad de elementos de cada fila y columna.

![matriz.png](attachment:matriz.png)

La matriz anterior “A” se dice que tiene una dimensión de “m” elementos por “n” elementos y también puede ser expresada utilizando dos subíndices (i, j) como:

![matriz02.png](attachment:matriz02.png)

En donde **i varía entre 1 y m**, y **j varía entre 1 y n.**
El proceso de acceso a los elementos de una matriz con conjuntos de enteros se denomina indexación.
En nuestro trabajo las matrices son un elemento fundamental, y al trabajar con software utilizamos el nombre de **array** como una abstracción de una matriz. Python no posee un objeto tipo array, por lo cual nos vamos a valer en principio de la librería **numpy** para poder trabajar con arrays. Hay que tener en cuenta que un array no es una lista, aun cuando a simple vista puedan existir similitudes.
En numpy expresaremos un array como A[i, j], esta librería admite todas las operaciones de matrices analizadas en álgebra lineal.

## Creamos un array con numpy

Para crear un array podemos importamos la librería de numpy y utilizamos el método “array()” de forma de pasar todos los elementos del array.

In [1]:
import numpy as np 

A = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9,10, 11, 12]])
print(A) 
print(type(A))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
<class 'numpy.ndarray'>


Como podemos ver jupyter nos retorna el resultado al imprimir en pantalla el array A y lo representa como una matriz.